# Generated by Django 4.1.3 on 2022-11-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_sneaker_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Release Date')),
                ('drop_type', models.CharField(choices=[('GR', 'General Release'), ('LR', 'Limited Release'), ('SD', 'Shock Drop')], default='GR', max_length=2)),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sneaker')),
            ],
        ),
    ]
